const TECH_WORDS = [
  'ABORT',
  'ADMIN',
  'AGILE',
  'ALERT',
  'ALIAS',
  'APPLE',
  'ARRAY',
  'AUDIO',
  'BASIC',
  'BATCH',
  'BLOBS',
  'BLOCK',
  'BOARD',
  'BOOTS',
  'BREAK',
  'BUILD',
  'BYTES',
  'CABLE',
  'CACHE',
  'CHIPS',
  'CLASS',
  'CLEAN',
  'CLICK',
  'CLOCK',
  'CLONE',
  'CLOUD',
  'CODED',
  'CODER',
  'CODES',
  'CRASH',
  'CRAWL',
  'CRYPT',
  'CYBER',
  'DATUM',
  'DEBUG',
  'DELAY',
  'DEPTH',
  'DRIVE',
  'EMAIL',
  'ENTER',
  'ERASE',
  'ERROR',
  'EXCEL',
  'FAULT',
  'FETCH',
  'FILES',
  'FLASH',
  'FLUSH',
  'FIBRE',
  'FOCUS',
  'FORKS',
  'FORUM',
  'FRAME',
  'GATES',
  'GRAPH',
  'HOSTS',
  'HTTPS',
  'IMAGE',
  'INDEX',
  'INPUT',
  'INTEL',
  'JOINS',
  'LASER',
  'LAYER',
  'LINKS',
  'LINUX',
  'LOGIC',
  'LOGIN',
  'LOOPS',
  'MACOS',
  'MACRO',
  'MEDIA',
  'MERGE',
  'MINER',
  'MODEL',
  'MODEM',
  'MONGO',
  'MOUNT',
  'MOUSE',
  'MUTEX',
  'NODES',
  'NULLS',
  'OCTAL',
  'PANEL',
  'PARSE',
  'PASTE',
  'PATCH',
  'PHONE',
  'PINGS',
  'PIPES',
  'PIVOT',
  'PIXEL',
  'PLUGS',
  'POLLS',
  'POOLS',
  'POPUP',
  'PORTS',
  'POWER',
  'PRINT',
  'PROXY',
  'PULLS',
  'QUERY',
  'QUEUE',
  'QUOTA',
  'RADAR',
  'RADIO',
  'RANGE',
  'REACT',
  'READS',
  'REGEX',
  'REPOS',
  'RESET',
  'RETRY',
  'ROBOT',
  'ROOTS',
  'ROUTE',
  'RULES',
  'SAVES',
  'SCALA',
  'SCALE',
  'SCOPE',
  'SCRUM',
  'SERVE',
  'SETUP',
  'SHELL',
  'SHIFT',
  'SITES',
  'SLEEP',
  'SLICE',
  'SMART',
  'SOLID',
  'SPOOF',
  'STACK',
  'STATE',
  'STATS',
  'STEAM',
  'STORE',
  'SWIFT',
  'SWIPE',
  'SYNCS',
  'TABLE',
  'TASKS',
  'THEME',
  'THROW',
  'TOKEN',
  'TOOLS',
  'TRACK',
  'TREES',
  'TUPLE',
  'TYPES',
  'UNZIP',
  'USERS',
  'VALVE',
  'VIEWS',
  'VIRUS',
  'WATCH',
  'WEBGL',
  'WIRES',
  'YIELD',
]

// The salt keeps the daily word unpredictable from the public source alone.
// `WORDLE_SECRET` is optional; falling back to `PAYLOAD_SECRET` means no new
// deployment configuration is strictly required. Only ever read server-side.
const getDailyWordSalt = (): string => process.env.WORDLE_SECRET || process.env.PAYLOAD_SECRET || ''

export function getDailyWord(): string {
  const input = `${new Date().toISOString().split('T')[0]}:${getDailyWordSalt()}`
  let hash = 5381
  for (let i = 0; i < input.length; i++) {
    hash = ((hash << 5) + hash + input.charCodeAt(i)) | 0
  }
  return TECH_WORDS[(hash >>> 0) % TECH_WORDS.length]
}

export function getTodayDate(): string {
  return new Date().toISOString().split('T')[0]
}

export function getPuzzleNumber(): number {
  const epoch = new Date('2026-01-01')
  const today = new Date()
  const diff = Math.floor((today.getTime() - epoch.getTime()) / (1000 * 60 * 60 * 24))
  return diff + 1
}
